//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.InteractionGallery.KinectBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        public album()
        {
            this.canciones = new HashSet<canciones>();
        }
    
        public int idAlbum { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaLanzamiento { get; set; }
        public Nullable<int> idGenero { get; set; }
        public Nullable<int> idDisquera { get; set; }
        public string cover { get; set; }
    
        public virtual disquera disquera { get; set; }
        public virtual genero genero { get; set; }
        public virtual ICollection<canciones> canciones { get; set; }
    }
}
