//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.InteractionGallery.KinectBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class canciones
    {
        public canciones()
        {
            this.rating = new HashSet<rating>();
        }
    
        public int idCancion { get; set; }
        public string nombre { get; set; }
        public int idAlbum { get; set; }
        public int idArtista { get; set; }
        public string claveAudio { get; set; }
        public string claveVideo { get; set; }
        public string source { get; set; }
    
        public virtual album album { get; set; }
        public virtual artista artista { get; set; }
        public virtual ICollection<rating> rating { get; set; }
    }
}
