//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.InteractionGallery.KinectBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class disquera
    {
        public disquera()
        {
            this.album = new HashSet<album>();
        }
    
        public int idDisquera { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<album> album { get; set; }
    }
}
