//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("kinectModel", "FK__album__idDisquer__0CBAE877", "disquera", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.disquera), "album", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.album), true)]
[assembly: EdmRelationshipAttribute("kinectModel", "FK__album__idGenero__0DAF0CB0", "genero", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.genero), "album", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.album), true)]
[assembly: EdmRelationshipAttribute("kinectModel", "FK__canciones__idAlb__1273C1CD", "album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.album), "canciones", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.canciones), true)]
[assembly: EdmRelationshipAttribute("kinectModel", "FK_album_artista", "artista", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.artista), "album", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.album), true)]
[assembly: EdmRelationshipAttribute("kinectModel", "FK__canciones__idArt__1367E606", "artista", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.artista), "canciones", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.canciones), true)]
[assembly: EdmRelationshipAttribute("kinectModel", "FK__rating__idCancio__182C9B23", "canciones", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.canciones), "rating", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Microsoft.Samples.Kinect.InteractionGallery.KinectBO.rating), true)]

#endregion

namespace Microsoft.Samples.Kinect.InteractionGallery.KinectBO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class kinectEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new kinectEntities1 object using the connection string found in the 'kinectEntities1' section of the application configuration file.
        /// </summary>
        public kinectEntities1() : base("name=kinectEntities1", "kinectEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new kinectEntities1 object.
        /// </summary>
        public kinectEntities1(string connectionString) : base(connectionString, "kinectEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new kinectEntities1 object.
        /// </summary>
        public kinectEntities1(EntityConnection connection) : base(connection, "kinectEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<album> album
        {
            get
            {
                if ((_album == null))
                {
                    _album = base.CreateObjectSet<album>("album");
                }
                return _album;
            }
        }
        private ObjectSet<album> _album;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<artista> artista
        {
            get
            {
                if ((_artista == null))
                {
                    _artista = base.CreateObjectSet<artista>("artista");
                }
                return _artista;
            }
        }
        private ObjectSet<artista> _artista;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<canciones> canciones
        {
            get
            {
                if ((_canciones == null))
                {
                    _canciones = base.CreateObjectSet<canciones>("canciones");
                }
                return _canciones;
            }
        }
        private ObjectSet<canciones> _canciones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<disquera> disquera
        {
            get
            {
                if ((_disquera == null))
                {
                    _disquera = base.CreateObjectSet<disquera>("disquera");
                }
                return _disquera;
            }
        }
        private ObjectSet<disquera> _disquera;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<genero> genero
        {
            get
            {
                if ((_genero == null))
                {
                    _genero = base.CreateObjectSet<genero>("genero");
                }
                return _genero;
            }
        }
        private ObjectSet<genero> _genero;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rating> rating
        {
            get
            {
                if ((_rating == null))
                {
                    _rating = base.CreateObjectSet<rating>("rating");
                }
                return _rating;
            }
        }
        private ObjectSet<rating> _rating;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the album EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToalbum(album album)
        {
            base.AddObject("album", album);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the artista EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToartista(artista artista)
        {
            base.AddObject("artista", artista);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the canciones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocanciones(canciones canciones)
        {
            base.AddObject("canciones", canciones);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the disquera EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodisquera(disquera disquera)
        {
            base.AddObject("disquera", disquera);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the genero EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogenero(genero genero)
        {
            base.AddObject("genero", genero);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rating EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorating(rating rating)
        {
            base.AddObject("rating", rating);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinectModel", Name="album")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class album : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new album object.
        /// </summary>
        /// <param name="idAlbum">Initial value of the idAlbum property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        public static album Createalbum(global::System.Int32 idAlbum, global::System.String nombre)
        {
            album album = new album();
            album.idAlbum = idAlbum;
            album.nombre = nombre;
            return album;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAlbum
        {
            get
            {
                return _idAlbum;
            }
            set
            {
                if (_idAlbum != value)
                {
                    OnidAlbumChanging(value);
                    ReportPropertyChanging("idAlbum");
                    _idAlbum = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idAlbum");
                    OnidAlbumChanged();
                }
            }
        }
        private global::System.Int32 _idAlbum;
        partial void OnidAlbumChanging(global::System.Int32 value);
        partial void OnidAlbumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaLanzamiento
        {
            get
            {
                return _fechaLanzamiento;
            }
            set
            {
                OnfechaLanzamientoChanging(value);
                ReportPropertyChanging("fechaLanzamiento");
                _fechaLanzamiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaLanzamiento");
                OnfechaLanzamientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaLanzamiento;
        partial void OnfechaLanzamientoChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaLanzamientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idGenero
        {
            get
            {
                return _idGenero;
            }
            set
            {
                OnidGeneroChanging(value);
                ReportPropertyChanging("idGenero");
                _idGenero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idGenero");
                OnidGeneroChanged();
            }
        }
        private Nullable<global::System.Int32> _idGenero;
        partial void OnidGeneroChanging(Nullable<global::System.Int32> value);
        partial void OnidGeneroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idDisquera
        {
            get
            {
                return _idDisquera;
            }
            set
            {
                OnidDisqueraChanging(value);
                ReportPropertyChanging("idDisquera");
                _idDisquera = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idDisquera");
                OnidDisqueraChanged();
            }
        }
        private Nullable<global::System.Int32> _idDisquera;
        partial void OnidDisqueraChanging(Nullable<global::System.Int32> value);
        partial void OnidDisqueraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cover
        {
            get
            {
                return _cover;
            }
            set
            {
                OncoverChanging(value);
                ReportPropertyChanging("cover");
                _cover = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cover");
                OncoverChanged();
            }
        }
        private global::System.String _cover;
        partial void OncoverChanging(global::System.String value);
        partial void OncoverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idArtista
        {
            get
            {
                return _idArtista;
            }
            set
            {
                OnidArtistaChanging(value);
                ReportPropertyChanging("idArtista");
                _idArtista = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idArtista");
                OnidArtistaChanged();
            }
        }
        private Nullable<global::System.Int32> _idArtista;
        partial void OnidArtistaChanging(Nullable<global::System.Int32> value);
        partial void OnidArtistaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__album__idDisquer__0CBAE877", "disquera")]
        public disquera disquera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<disquera>("kinectModel.FK__album__idDisquer__0CBAE877", "disquera").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<disquera>("kinectModel.FK__album__idDisquer__0CBAE877", "disquera").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<disquera> disqueraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<disquera>("kinectModel.FK__album__idDisquer__0CBAE877", "disquera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<disquera>("kinectModel.FK__album__idDisquer__0CBAE877", "disquera", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__album__idGenero__0DAF0CB0", "genero")]
        public genero genero
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<genero>("kinectModel.FK__album__idGenero__0DAF0CB0", "genero").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<genero>("kinectModel.FK__album__idGenero__0DAF0CB0", "genero").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<genero> generoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<genero>("kinectModel.FK__album__idGenero__0DAF0CB0", "genero");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<genero>("kinectModel.FK__album__idGenero__0DAF0CB0", "genero", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__canciones__idAlb__1273C1CD", "canciones")]
        public EntityCollection<canciones> canciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<canciones>("kinectModel.FK__canciones__idAlb__1273C1CD", "canciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<canciones>("kinectModel.FK__canciones__idAlb__1273C1CD", "canciones", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK_album_artista", "artista")]
        public artista artista
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<artista>("kinectModel.FK_album_artista", "artista").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<artista>("kinectModel.FK_album_artista", "artista").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<artista> artistaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<artista>("kinectModel.FK_album_artista", "artista");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<artista>("kinectModel.FK_album_artista", "artista", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinectModel", Name="artista")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class artista : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new artista object.
        /// </summary>
        /// <param name="idArtista">Initial value of the idArtista property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        public static artista Createartista(global::System.Int32 idArtista, global::System.String nombre)
        {
            artista artista = new artista();
            artista.idArtista = idArtista;
            artista.nombre = nombre;
            return artista;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idArtista
        {
            get
            {
                return _idArtista;
            }
            set
            {
                if (_idArtista != value)
                {
                    OnidArtistaChanging(value);
                    ReportPropertyChanging("idArtista");
                    _idArtista = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idArtista");
                    OnidArtistaChanged();
                }
            }
        }
        private global::System.Int32 _idArtista;
        partial void OnidArtistaChanging(global::System.Int32 value);
        partial void OnidArtistaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String picture
        {
            get
            {
                return _picture;
            }
            set
            {
                OnpictureChanging(value);
                ReportPropertyChanging("picture");
                _picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("picture");
                OnpictureChanged();
            }
        }
        private global::System.String _picture;
        partial void OnpictureChanging(global::System.String value);
        partial void OnpictureChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK_album_artista", "album")]
        public EntityCollection<album> album
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<album>("kinectModel.FK_album_artista", "album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<album>("kinectModel.FK_album_artista", "album", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__canciones__idArt__1367E606", "canciones")]
        public EntityCollection<canciones> canciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<canciones>("kinectModel.FK__canciones__idArt__1367E606", "canciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<canciones>("kinectModel.FK__canciones__idArt__1367E606", "canciones", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinectModel", Name="canciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class canciones : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new canciones object.
        /// </summary>
        /// <param name="idCancion">Initial value of the idCancion property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="idAlbum">Initial value of the idAlbum property.</param>
        /// <param name="idArtista">Initial value of the idArtista property.</param>
        public static canciones Createcanciones(global::System.Int32 idCancion, global::System.String nombre, global::System.Int32 idAlbum, global::System.Int32 idArtista)
        {
            canciones canciones = new canciones();
            canciones.idCancion = idCancion;
            canciones.nombre = nombre;
            canciones.idAlbum = idAlbum;
            canciones.idArtista = idArtista;
            return canciones;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCancion
        {
            get
            {
                return _idCancion;
            }
            set
            {
                if (_idCancion != value)
                {
                    OnidCancionChanging(value);
                    ReportPropertyChanging("idCancion");
                    _idCancion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCancion");
                    OnidCancionChanged();
                }
            }
        }
        private global::System.Int32 _idCancion;
        partial void OnidCancionChanging(global::System.Int32 value);
        partial void OnidCancionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAlbum
        {
            get
            {
                return _idAlbum;
            }
            set
            {
                OnidAlbumChanging(value);
                ReportPropertyChanging("idAlbum");
                _idAlbum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idAlbum");
                OnidAlbumChanged();
            }
        }
        private global::System.Int32 _idAlbum;
        partial void OnidAlbumChanging(global::System.Int32 value);
        partial void OnidAlbumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idArtista
        {
            get
            {
                return _idArtista;
            }
            set
            {
                OnidArtistaChanging(value);
                ReportPropertyChanging("idArtista");
                _idArtista = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idArtista");
                OnidArtistaChanged();
            }
        }
        private global::System.Int32 _idArtista;
        partial void OnidArtistaChanging(global::System.Int32 value);
        partial void OnidArtistaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String claveAudio
        {
            get
            {
                return _claveAudio;
            }
            set
            {
                OnclaveAudioChanging(value);
                ReportPropertyChanging("claveAudio");
                _claveAudio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("claveAudio");
                OnclaveAudioChanged();
            }
        }
        private global::System.String _claveAudio;
        partial void OnclaveAudioChanging(global::System.String value);
        partial void OnclaveAudioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String claveVideo
        {
            get
            {
                return _claveVideo;
            }
            set
            {
                OnclaveVideoChanging(value);
                ReportPropertyChanging("claveVideo");
                _claveVideo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("claveVideo");
                OnclaveVideoChanged();
            }
        }
        private global::System.String _claveVideo;
        partial void OnclaveVideoChanging(global::System.String value);
        partial void OnclaveVideoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String source
        {
            get
            {
                return _source;
            }
            set
            {
                OnsourceChanging(value);
                ReportPropertyChanging("source");
                _source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("source");
                OnsourceChanged();
            }
        }
        private global::System.String _source;
        partial void OnsourceChanging(global::System.String value);
        partial void OnsourceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__canciones__idAlb__1273C1CD", "album")]
        public album album
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<album>("kinectModel.FK__canciones__idAlb__1273C1CD", "album").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<album>("kinectModel.FK__canciones__idAlb__1273C1CD", "album").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<album> albumReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<album>("kinectModel.FK__canciones__idAlb__1273C1CD", "album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<album>("kinectModel.FK__canciones__idAlb__1273C1CD", "album", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__canciones__idArt__1367E606", "artista")]
        public artista artista
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<artista>("kinectModel.FK__canciones__idArt__1367E606", "artista").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<artista>("kinectModel.FK__canciones__idArt__1367E606", "artista").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<artista> artistaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<artista>("kinectModel.FK__canciones__idArt__1367E606", "artista");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<artista>("kinectModel.FK__canciones__idArt__1367E606", "artista", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__rating__idCancio__182C9B23", "rating")]
        public EntityCollection<rating> rating
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<rating>("kinectModel.FK__rating__idCancio__182C9B23", "rating");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<rating>("kinectModel.FK__rating__idCancio__182C9B23", "rating", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinectModel", Name="disquera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class disquera : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new disquera object.
        /// </summary>
        /// <param name="idDisquera">Initial value of the idDisquera property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        public static disquera Createdisquera(global::System.Int32 idDisquera, global::System.String nombre)
        {
            disquera disquera = new disquera();
            disquera.idDisquera = idDisquera;
            disquera.nombre = nombre;
            return disquera;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idDisquera
        {
            get
            {
                return _idDisquera;
            }
            set
            {
                if (_idDisquera != value)
                {
                    OnidDisqueraChanging(value);
                    ReportPropertyChanging("idDisquera");
                    _idDisquera = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idDisquera");
                    OnidDisqueraChanged();
                }
            }
        }
        private global::System.Int32 _idDisquera;
        partial void OnidDisqueraChanging(global::System.Int32 value);
        partial void OnidDisqueraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__album__idDisquer__0CBAE877", "album")]
        public EntityCollection<album> album
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<album>("kinectModel.FK__album__idDisquer__0CBAE877", "album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<album>("kinectModel.FK__album__idDisquer__0CBAE877", "album", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinectModel", Name="genero")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class genero : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new genero object.
        /// </summary>
        /// <param name="idGenero">Initial value of the idGenero property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        public static genero Creategenero(global::System.Int32 idGenero, global::System.String nombre)
        {
            genero genero = new genero();
            genero.idGenero = idGenero;
            genero.nombre = nombre;
            return genero;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idGenero
        {
            get
            {
                return _idGenero;
            }
            set
            {
                if (_idGenero != value)
                {
                    OnidGeneroChanging(value);
                    ReportPropertyChanging("idGenero");
                    _idGenero = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idGenero");
                    OnidGeneroChanged();
                }
            }
        }
        private global::System.Int32 _idGenero;
        partial void OnidGeneroChanging(global::System.Int32 value);
        partial void OnidGeneroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cover
        {
            get
            {
                return _cover;
            }
            set
            {
                OncoverChanging(value);
                ReportPropertyChanging("cover");
                _cover = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cover");
                OncoverChanged();
            }
        }
        private global::System.String _cover;
        partial void OncoverChanging(global::System.String value);
        partial void OncoverChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__album__idGenero__0DAF0CB0", "album")]
        public EntityCollection<album> album
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<album>("kinectModel.FK__album__idGenero__0DAF0CB0", "album");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<album>("kinectModel.FK__album__idGenero__0DAF0CB0", "album", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinectModel", Name="rating")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rating : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rating object.
        /// </summary>
        /// <param name="idRating">Initial value of the idRating property.</param>
        public static rating Createrating(global::System.Int32 idRating)
        {
            rating rating = new rating();
            rating.idRating = idRating;
            return rating;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idRating
        {
            get
            {
                return _idRating;
            }
            set
            {
                if (_idRating != value)
                {
                    OnidRatingChanging(value);
                    ReportPropertyChanging("idRating");
                    _idRating = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idRating");
                    OnidRatingChanged();
                }
            }
        }
        private global::System.Int32 _idRating;
        partial void OnidRatingChanging(global::System.Int32 value);
        partial void OnidRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idCancion
        {
            get
            {
                return _idCancion;
            }
            set
            {
                OnidCancionChanging(value);
                ReportPropertyChanging("idCancion");
                _idCancion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCancion");
                OnidCancionChanged();
            }
        }
        private Nullable<global::System.Int32> _idCancion;
        partial void OnidCancionChanging(Nullable<global::System.Int32> value);
        partial void OnidCancionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> likes
        {
            get
            {
                return _likes;
            }
            set
            {
                OnlikesChanging(value);
                ReportPropertyChanging("likes");
                _likes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("likes");
                OnlikesChanged();
            }
        }
        private Nullable<global::System.Int32> _likes;
        partial void OnlikesChanging(Nullable<global::System.Int32> value);
        partial void OnlikesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kinectModel", "FK__rating__idCancio__182C9B23", "canciones")]
        public canciones canciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<canciones>("kinectModel.FK__rating__idCancio__182C9B23", "canciones").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<canciones>("kinectModel.FK__rating__idCancio__182C9B23", "canciones").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<canciones> cancionesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<canciones>("kinectModel.FK__rating__idCancio__182C9B23", "canciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<canciones>("kinectModel.FK__rating__idCancio__182C9B23", "canciones", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
