//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.InteractionGallery.KinectBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int idRating { get; set; }
        public Nullable<int> idCancion { get; set; }
        public Nullable<int> likes { get; set; }
    
        public virtual canciones canciones { get; set; }
    }
}
